**Practical 1 | Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas**

**Step 1 : Import Pandas**

In [25]:
# Import the Pandas library
import pandas as pd

**step 2: Create Data**

In [26]:
# Create raw data dictionary
data = {
    "ID" : [101, 102, 103, 104, 105, 106, 107],
    "Name" : ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krisha", "Harry"],
    "Age" : [20,21,19,20,22,24,28],
    "City" : ["Surat", "Navsari", "Valsad", "Bharuch", "Surat", "Gandhinagar", "Ahmedabad"],
    "Marks" : [85, 92, 78, 88, 81, 84, 90]
}

**Step 3: Create a DataFrame**

In [27]:
# Create a DataFrame from the dictionar
df = pd.DataFrame(data)
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Step 4 : Save Data as CSV File**

In [28]:
# Save data as a CSV file
df.to_csv("student.csv", index=False)
print("CSV file created successfully")

CSV file created successfully

**Step 5 : Save Data as Excel File**

In [29]:
# Save data as an Excel file
df.to_excel("student.xlsx", index=False)
print("Excel file created successfully")

Excel file created successfully

**Step 6 : Save Data as JSON File**

In [30]:
# Save data as a JSON file
df.to_json("student.json", orient="records", indent=4)
print("JSON file created successfully")

JSON file created successfully

****

**step 7 :Read the CSV File**

In [31]:
# Read data back from the CSV file
df_csv = pd.read_csv("student.csv")
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**step 8 :Read the Excel File**

In [32]:
# Read data back from the Excel file
df_excel = pd.read_excel("student.xlsx")
df_excel

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**step 9:Read the JSON File**

In [33]:
# Read data back from the JSON file
df_json = pd.read_json("student.json")
df_json

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**step:10 Display First Five Records**

In [34]:
# First 5 records from csv file with the help of head()
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

**step 11 :Display the Last Five Records**

In [35]:
# Last 5 records from CSV file using tail()
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Step 12 : Display Dataset Info**

In [36]:
# Display dataset summary and memory info
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

**step13 :Display Statistical Summary**

In [37]:
# Display statistical summary (mean, min, max, etc.)
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

**Step 14 : Display Dataset Shape**

In [38]:
# Get total number of rows and columns
df_csv.shape

(7, 5)

**Step 15 : Display Column Names**

In [39]:
# Display all column names
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step 16 : Display Data Types**

In [40]:
# Display the data type of each column
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step 17 : Check for Missing Values**

In [41]:
# Check for missing (null) values in each column
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step 18 : Display a single column**

In [42]:
# Select and display a single column
df_csv["Name"]

0     Rahul
1     Priya
2      Amit
3      Riya
4     Karan
5    Krisha
6     Harry
Name: Name, dtype: object

**step 19:Display Multiple Columns**

In [43]:
# Select and display a single column
df_csv[["Name", "Age"]]

     Name  Age
0   Rahul   20
1   Priya   21
2    Amit   19
3    Riya   20
4   Karan   22
5  Krisha   24
6   Harry   28

**Step 20 : Filter Records**

In [44]:
# Filter records where Marks are greater than 85
df_csv[df_csv['Marks'] > 85]

    ID   Name  Age       City  Marks
1  102  Priya   21    Navsari     92
3  104   Riya   20    Bharuch     88
6  107  Harry   28  Ahmedabad     90

**Step 21 : Calculate Average Marks**

In [45]:
# Calculate the average (mean) marks
df_csv['Marks'].mean()

np.float64(85.42857142857143)

**Step 22 : Sort Data**

In [46]:
# Sort dataset by Marks in descending order
df_csv.sort_values(by='Marks', ascending=False)

    ID    Name  Age         City  Marks
1  102   Priya   21      Navsari     92
6  107   Harry   28    Ahmedabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78

**step23 :Display DF**

In [47]:
# Print the full DataFrame
print(df_csv)

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90